steps:
    - label: ":hammer: Example Script"
      command: "./scripts.sh"
    #   artifact_paths: "artifacts/*"

    - wait

    - block: "Deploy"
      prompt: "Deploy to production?"

    - label: "🚀"
      trigger: "my-app-deploy"
      if: build.branch == 'master'
      build:
        commit: "$BUILDKITE_COMMIT"
